# Generated by Django 3.2.4 on 2021-07-04 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='number_course', to='groups.group')),
            ],
        ),
    ]
