# Generated by Django 3.2.4 on 2021-07-03 23:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import groups.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=120, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('birthday', models.DateField(default=datetime.date.today, validators=[groups.validators.adult_validation])),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
