# Generated by Django 3.2.4 on 2021-07-03 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_alter_course_course'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='number_course', to='Courses.course'),
        ),
    ]
