# Generated by Django 3.2.4 on 2021-06-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='phone_number',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
