# Generated by Django 3.2.4 on 2021-06-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='email',
            field=models.EmailField(max_length=120, null=True),
        ),
    ]
