# Generated by Django 3.2.4 on 2021-06-09 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
